---
- name: Run the playbook tasks on the localhost
  hosts: all
  become: yes
  tasks:

  - name: Print hostname of target
    command: hostname

  - name: Install aptitude if not there
    command: apt-get -y install aptitude
  
  - name: Update the apt package index
    apt: update_cache=yes

  - name: Upgrade system packages
    apt: upgrade=yes
    